version: '3.9'

services:
  postgres_v2:
    image: postgres:16-alpine
    container_name: flightgo_postgres_v3
    restart: unless-stopped
    environment:
      POSTGRES_USER: flightgo
      POSTGRES_PASSWORD: flightgo_dev_pass
      POSTGRES_DB: flightgo_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U flightgo']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flightgo_redis
    restart: unless-stopped
    command: redis-server --requirepass redis_dev_pass
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'redis_dev_pass', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
